version: '3'

services:
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - .C:/Users/Fabrício-PC/Documents/Códigos/dashboard/api/docker/dashboard.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge